export type Language = "fr" | "en";

const translations = {
  fr: {
    app: { name: "Wealthia", tagline: "Gestion de Patrimoine" },
    demo: {
      banner: "Mode Démo — vos données ne sont pas sauvegardées",
      cta: "S'inscrire gratuitement →",
      button: "✦ Essayer la démo gratuitement",
      writeBlocked: "Action désactivée en mode démo",
    },
    nav: {
      home: "Accueil",
      transactions: "Transactions",
      accounts: "Comptes",
      stocks: "Bourse",
      advisor: "Conseiller",
    },
    home: {
      hello: "Bonjour,",
      overview: "Aperçu de vos finances",
      totalBalance: "Solde Total",
      income: "Revenus",
      expenses: "Dépenses",
      myAccounts: "Mes Comptes",
      monthExpenses: "Dépenses du Mois",
      seeAll: "Voir tout",
      percentOfTotal: "{p}% du total",
      quickAdd: "Ajouter",
      quickReports: "Rapports",
      quickAI: "IA",
      quickStocks: "Bourse",
    },
    auth: {
      google: "Continuer avec Google",
      or: "ou",
      email: "Adresse email",
      password: "Mot de passe",
      name: "Nom",
      login: "Se connecter",
      signup: "S'inscrire",
      magicLink: "Connexion par lien magique",
      magicSent: "Lien magique envoyé ! Vérifiez votre boîte mail.",
      noAccount: "Pas encore de compte ?",
      haveAccount: "Déjà un compte ?",
    },
    transactions: {
      title: "Transactions",
      empty: "Aucune transaction",
      emptyHint: "Ajoutez votre première dépense avec le bouton +",
      loadMore: "Charger plus",
      aiBadge: "IA",
      filter: {
        all: "Toutes",
        income: "Revenus",
        expense: "Dépenses",
      },
      add: {
        titleExpense: "Nouvelle dépense",
        titleIncome: "Nouveau revenu",
        amount: "Montant",
        label: "Libellé",
        labelPlaceholder: "Ex. Courses Carrefour",
        category: "Catégorie",
        account: "Compte",
        noAccount: "Aucun compte",
        date: "Date",
        notes: "Notes",
        addNote: "Ajouter une note",
        submit: "Enregistrer",
        type: {
          expense: "Dépense",
          income: "Revenu",
        },
      },
      delete: {
        confirm: "Supprimer cette transaction ?",
        confirmCta: "Supprimer",
        cancel: "Annuler",
      },
    },
    accounts: {
      title: "Comptes",
      add: "Ajouter",
      sectionAccounts: "Comptes bancaires",
      sectionBudgets: "Budgets Mensuels",
      sectionDebts: "Dettes & Prêts",
      sectionSubscriptions: "Abonnements",
      emptyAccounts: "Aucun compte ajouté",
      emptyBudgets: "Aucun budget défini",
      emptyDebts: "Aucune dette enregistrée",
      emptySubscriptions: "Aucun abonnement suivi",
      name: "Nom",
      initialBalance: "Solde initial",
      currency: "Devise",
      typeChecking: "Courant",
      typeSavings: "Épargne",
      typeBooklet: "Livret",
      typeCash: "Liquide",
      typeOther: "Autre",
      addAccountTitle: "Nouveau compte",
      addBudgetTitle: "Nouveau budget",
      addDebtTitle: "Nouvelle dette",
      addSubTitle: "Nouvel abonnement",
      deleteConfirm: "Supprimer cet élément ?",
      cancel: "Annuler",
      delete: "Supprimer",
      save: "Enregistrer",
    },
    budgets: {
      over: "Dépassement de",
      remaining: "restants",
      category: "Catégorie",
      cap: "Plafond",
      period: "Période",
      periodMonthly: "Mensuel",
      periodWeekly: "Hebdomadaire",
    },
    debts: {
      typeDebt: "Dette",
      typeLoan: "Prêt",
      total: "Montant total",
      remaining: "Restant dû",
      dueDate: "Échéance",
      label: "Libellé",
    },
    subscriptions: {
      name: "Nom",
      amount: "Montant",
      freq: "Fréquence",
      freqMonthly: "Mensuel",
      freqYearly: "Annuel",
      freqWeekly: "Hebdomadaire",
      nextBilling: "Prochain prélèvement",
      category: "Catégorie",
    },
    stub: {
      soon: "Bientôt disponible",
      soonDesc: "Cette section est en cours de construction.",
    },
    stocks: {
      title: "Bourse & Épargne",
      portfolio: "Mon Portefeuille",
      goals: "Objectifs d'Épargne",
      portfolioValue: "Valeur du Portefeuille",
      latentGain: "Plus-value latente",
      lastUpdated: "Mis à jour à",
      refresh: "Actualiser",
      realtime: "Cours en temps réel",
      emptyPortfolio: "Aucun actif suivi",
      emptyGoals: "Aucun objectif défini",
      addAsset: "Nouvel actif",
      addGoal: "Nouvel objectif",
      purchasePrice: "Prix d'achat",
      currentPrice: "Prix actuel",
      quantity: "Quantité",
      ticker: "Symbole / Ticker",
      assetName: "Nom de l'actif",
      assetType: "Type",
      typeStock: "Action",
      typeETF: "ETF",
      typeCrypto: "Crypto",
      typeOther: "Autre",
      totalInvested: "Total investi",
      dateAdded: "Ajouté le",
      goalReached: "✓ Objectif atteint !",
      goalRemaining: "restants",
      goalDue: "Échéance",
      addFunds: "+ Ajouter des fonds",
      goalName: "Nom de l'objectif",
      targetAmount: "Montant cible",
      currentAmount: "Montant actuel",
      goalIcon: "Icône",
      goalDate: "Échéance (optionnelle)",
      deleteAssetConfirm: "Supprimer cet actif ?",
      deleteGoalConfirm: "Supprimer cet objectif ?",
      searching: "Recherche…",
    },
    paywall: {
      title: "Fonctionnalité Premium",
      subtitle: "Passez à un plan supérieur pour accéder à cette fonctionnalité",
      monthly: "/ mois",
      yearly: "/ an",
      upgrade: "Passer à {plan}",
      later: "Plus tard",
      free: "Gratuit",
      pro: "Pro",
      max: "Max",
    },
    admin: {
      title: "Administration",
      badge: "ADMIN",
      users: "Utilisateurs",
      promoCodes: "Codes Promo",
      referrals: "Parrainage",
      totalUsers: "Utilisateurs",
      changePlan: "Changer de plan",
      planDuration: "Durée (jours)",
      permanent: "Permanent",
      apply: "Appliquer",
      createCode: "Créer le code",
      generateRandom: "Générer aléatoirement",
      maxUses: "Utilisations max",
      expiry: "Date d'expiration",
      deactivate: "Désactiver",
      copy: "Copier",
      copied: "Copié !",
      codeActive: "ACTIF",
      codeInactive: "INACTIF",
      uses: "Utilisations",
      search: "Rechercher un utilisateur…",
      noUsers: "Aucun utilisateur",
      noCodes: "Aucun code promo",
      noReferrals: "Aucun parrainage",
      registered: "Inscrit le",
      referredCount: "Filleuls",
      customCode: "Code personnalisé",
      totalReferrals: "Parrainages",
      rewardsGranted: "Récompenses",
      topReferrer: "Top parrain",
      referrer: "Parrain",
      referred: "Filleul",
      rewardYes: "Oui",
      rewardNo: "Non",
    },
    settings: {
      title: "Paramètres",
      profile: "Profil",
      plan: "Mon Plan",
      referral: "Parrainez un ami",
      referralTitle: "Parrainez un ami, gagnez 1 mois Pro",
      referralLink: "Votre lien unique",
      referralActive: "Filleuls actifs",
      referralRewards: "Récompenses gagnées",
      referralMonths: "mois",
      share: "Partager",
      promoCode: "Code Promo",
      promoPlaceholder: "Entrez votre code",
      promoApply: "Appliquer",
      promoSuccess: "Code appliqué — plan mis à jour !",
      promoError: "Code invalide ou déjà utilisé",
      language: "Langue",
      logout: "Se déconnecter",
      managePlan: "Gérer l'abonnement",
      planExpires: "Expire le",
      planPermanent: "Sans expiration",
    },
  },
  en: {
    app: { name: "Wealthia", tagline: "Wealth Management" },
    demo: {
      banner: "Demo Mode — your data is not saved",
      cta: "Sign up for free →",
      button: "✦ Try the demo",
      writeBlocked: "Action disabled in demo mode",
    },
    nav: {
      home: "Home",
      transactions: "Transactions",
      accounts: "Accounts",
      stocks: "Stocks",
      advisor: "Advisor",
    },
    home: {
      hello: "Hello,",
      overview: "Your financial overview",
      totalBalance: "Total Balance",
      income: "Income",
      expenses: "Expenses",
      myAccounts: "My Accounts",
      monthExpenses: "Monthly Expenses",
      seeAll: "See all",
      percentOfTotal: "{p}% of total",
      quickAdd: "Add",
      quickReports: "Reports",
      quickAI: "AI",
      quickStocks: "Stocks",
    },
    auth: {
      google: "Continue with Google",
      or: "or",
      email: "Email address",
      password: "Password",
      name: "Name",
      login: "Sign in",
      signup: "Sign up",
      magicLink: "Sign in with magic link",
      magicSent: "Magic link sent! Check your inbox.",
      noAccount: "No account yet?",
      haveAccount: "Already have an account?",
    },
    transactions: {
      title: "Transactions",
      empty: "No transactions",
      emptyHint: "Add your first expense with the + button",
      loadMore: "Load more",
      aiBadge: "AI",
      filter: {
        all: "All",
        income: "Income",
        expense: "Expenses",
      },
      add: {
        titleExpense: "New expense",
        titleIncome: "New income",
        amount: "Amount",
        label: "Label",
        labelPlaceholder: "E.g. Carrefour groceries",
        category: "Category",
        account: "Account",
        noAccount: "No account",
        date: "Date",
        notes: "Notes",
        addNote: "Add a note",
        submit: "Save",
        type: {
          expense: "Expense",
          income: "Income",
        },
      },
      delete: {
        confirm: "Delete this transaction?",
        confirmCta: "Delete",
        cancel: "Cancel",
      },
    },
    accounts: {
      title: "Accounts",
      add: "Add",
      sectionAccounts: "Bank accounts",
      sectionBudgets: "Monthly Budgets",
      sectionDebts: "Debts & Loans",
      sectionSubscriptions: "Subscriptions",
      emptyAccounts: "No accounts added",
      emptyBudgets: "No budgets set",
      emptyDebts: "No debts recorded",
      emptySubscriptions: "No subscriptions tracked",
      name: "Name",
      initialBalance: "Initial balance",
      currency: "Currency",
      typeChecking: "Checking",
      typeSavings: "Savings",
      typeBooklet: "Booklet",
      typeCash: "Cash",
      typeOther: "Other",
      addAccountTitle: "New account",
      addBudgetTitle: "New budget",
      addDebtTitle: "New debt",
      addSubTitle: "New subscription",
      deleteConfirm: "Delete this item?",
      cancel: "Cancel",
      delete: "Delete",
      save: "Save",
    },
    budgets: {
      over: "Over by",
      remaining: "left",
      category: "Category",
      cap: "Cap",
      period: "Period",
      periodMonthly: "Monthly",
      periodWeekly: "Weekly",
    },
    debts: {
      typeDebt: "Debt",
      typeLoan: "Loan",
      total: "Total amount",
      remaining: "Remaining",
      dueDate: "Due date",
      label: "Label",
    },
    subscriptions: {
      name: "Name",
      amount: "Amount",
      freq: "Frequency",
      freqMonthly: "Monthly",
      freqYearly: "Yearly",
      freqWeekly: "Weekly",
      nextBilling: "Next billing",
      category: "Category",
    },
    stub: {
      soon: "Coming soon",
      soonDesc: "This section is under construction.",
    },
    stocks: {
      title: "Stocks & Savings",
      portfolio: "My Portfolio",
      goals: "Savings Goals",
      portfolioValue: "Portfolio Value",
      latentGain: "Unrealized Gain",
      lastUpdated: "Updated at",
      refresh: "Refresh",
      realtime: "Live prices",
      emptyPortfolio: "No assets tracked",
      emptyGoals: "No savings goals",
      addAsset: "New asset",
      addGoal: "New goal",
      purchasePrice: "Purchase price",
      currentPrice: "Current price",
      quantity: "Quantity",
      ticker: "Symbol / Ticker",
      assetName: "Asset name",
      assetType: "Type",
      typeStock: "Stock",
      typeETF: "ETF",
      typeCrypto: "Crypto",
      typeOther: "Other",
      totalInvested: "Total invested",
      dateAdded: "Added on",
      goalReached: "✓ Goal reached!",
      goalRemaining: "left",
      goalDue: "Due",
      addFunds: "+ Add funds",
      goalName: "Goal name",
      targetAmount: "Target amount",
      currentAmount: "Current amount",
      goalIcon: "Icon",
      goalDate: "Due date (optional)",
      deleteAssetConfirm: "Delete this asset?",
      deleteGoalConfirm: "Delete this goal?",
      searching: "Searching…",
    },
    paywall: {
      title: "Premium Feature",
      subtitle: "Upgrade your plan to access this feature",
      monthly: "/ month",
      yearly: "/ year",
      upgrade: "Upgrade to {plan}",
      later: "Later",
      free: "Free",
      pro: "Pro",
      max: "Max",
    },
    admin: {
      title: "Administration",
      badge: "ADMIN",
      users: "Users",
      promoCodes: "Promo Codes",
      referrals: "Referrals",
      totalUsers: "Users",
      changePlan: "Change plan",
      planDuration: "Duration (days)",
      permanent: "Permanent",
      apply: "Apply",
      createCode: "Create code",
      generateRandom: "Generate random",
      maxUses: "Max uses",
      expiry: "Expiry date",
      deactivate: "Deactivate",
      copy: "Copy",
      copied: "Copied!",
      codeActive: "ACTIVE",
      codeInactive: "INACTIVE",
      uses: "Uses",
      search: "Search a user…",
      noUsers: "No users",
      noCodes: "No promo codes",
      noReferrals: "No referrals",
      registered: "Registered",
      referredCount: "Referrals",
      customCode: "Custom code",
      totalReferrals: "Referrals",
      rewardsGranted: "Rewards",
      topReferrer: "Top referrer",
      referrer: "Referrer",
      referred: "Referred",
      rewardYes: "Yes",
      rewardNo: "No",
    },
    settings: {
      title: "Settings",
      profile: "Profile",
      plan: "My Plan",
      referral: "Refer a friend",
      referralTitle: "Refer a friend, earn 1 month Pro",
      referralLink: "Your unique link",
      referralActive: "Active referrals",
      referralRewards: "Rewards earned",
      referralMonths: "months",
      share: "Share",
      promoCode: "Promo Code",
      promoPlaceholder: "Enter your code",
      promoApply: "Apply",
      promoSuccess: "Code applied — plan updated!",
      promoError: "Invalid or already used code",
      language: "Language",
      logout: "Sign out",
      managePlan: "Manage subscription",
      planExpires: "Expires on",
      planPermanent: "No expiry",
    },
  },
} as const;

export type Strings = typeof translations.fr;

function getNestedValue(obj: Record<string, unknown>, path: string): string {
  const keys = path.split(".");
  let current: unknown = obj;
  for (const key of keys) {
    if (current && typeof current === "object" && key in (current as Record<string, unknown>)) {
      current = (current as Record<string, unknown>)[key];
    } else {
      return path;
    }
  }
  return typeof current === "string" ? current : path;
}

function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) =>
    k in vars ? String(vars[k]) : `{${k}}`,
  );
}

function readLang(): Language {
  if (typeof window === "undefined") return "fr";
  const stored = window.localStorage.getItem("wealthia_lang");
  return stored === "en" ? "en" : "fr";
}

export function useTranslation() {
  const lang: Language = readLang();
  const strings = translations[lang];

  const t = (key: string, vars?: Record<string, string | number>): string => {
    const raw = getNestedValue(strings as unknown as Record<string, unknown>, key);
    return interpolate(raw, vars);
  };

  const setLanguage = (l: Language) => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem("wealthia_lang", l);
    window.location.reload();
  };

  return { t, strings, lang, setLanguage };
}
