export type Language = "fr" | "en";

const translations = {
  fr: {
    app: { name: "Wealthia", tagline: "Gestion de Patrimoine" },
    demo: {
      banner: "Mode Démo — vos données ne sont pas sauvegardées",
      cta: "S'inscrire gratuitement →",
      button: "✦ Essayer la démo gratuitement",
      writeBlocked: "Action désactivée en mode démo",
    },
    nav: {
      home: "Accueil",
      transactions: "Transactions",
      accounts: "Comptes",
      stocks: "Bourse",
      advisor: "Conseiller",
    },
    home: {
      hello: "Aperçu de votre patrimoine",
      overview: "Suivez vos comptes, budgets et investissements en un coup d'œil",
      totalBalance: "Solde Total",
      income: "Revenus",
      expenses: "Dépenses",
      myAccounts: "Mes Comptes",
      monthExpenses: "Dépenses du Mois",
      seeAll: "Voir tout",
      percentOfTotal: "{p}% du total",
      quickAdd: "Ajouter",
      quickReports: "Rapports",
      quickAI: "IA",
      quickStocks: "Bourse",
    },
    auth: {
      google: "Continuer avec Google",
      or: "ou",
      email: "Adresse email",
      password: "Mot de passe",
      name: "Nom",
      login: "Se connecter",
      signup: "S'inscrire",
      magicLink: "Connexion par lien magique",
      magicSent: "Lien magique envoyé ! Vérifiez votre boîte mail.",
      noAccount: "Pas encore de compte ?",
      haveAccount: "Déjà un compte ?",
    },
    transactions: {
      title: "Transactions",
      empty: "Aucune transaction",
      emptyHint: "Ajoutez votre première dépense avec le bouton +",
      loadMore: "Charger plus",
      aiBadge: "IA",
      filter: {
        all: "Toutes",
        income: "Revenus",
        expense: "Dépenses",
      },
      add: {
        titleExpense: "Nouvelle dépense",
        titleIncome: "Nouveau revenu",
        amount: "Montant",
        label: "Libellé",
        labelPlaceholder: "Ex. Courses Carrefour",
        category: "Catégorie",
        account: "Compte",
        noAccount: "Aucun compte",
        date: "Date",
        notes: "Notes",
        addNote: "Ajouter une note",
        submit: "Enregistrer",
        type: {
          expense: "Dépense",
          income: "Revenu",
        },
      },
      delete: {
        confirm: "Supprimer cette transaction ?",
        confirmCta: "Supprimer",
        cancel: "Annuler",
      },
    },
    accounts: {
      title: "Comptes",
      add: "Ajouter",
      sectionAccounts: "Comptes bancaires",
      sectionBudgets: "Budgets Mensuels",
      sectionDebts: "Dettes & Prêts",
      sectionSubscriptions: "Abonnements",
      emptyAccounts: "Aucun compte ajouté",
      emptyBudgets: "Aucun budget défini",
      emptyDebts: "Aucune dette enregistrée",
      emptySubscriptions: "Aucun abonnement suivi",
      name: "Nom",
      initialBalance: "Solde initial",
      currency: "Devise",
      typeChecking: "Courant",
      typeSavings: "Épargne",
      typeBooklet: "Livret",
      typeCash: "Liquide",
      typeOther: "Autre",
      addAccountTitle: "Nouveau compte",
      addBudgetTitle: "Nouveau budget",
      addDebtTitle: "Nouvelle dette",
      addSubTitle: "Nouvel abonnement",
      deleteConfirm: "Supprimer cet élément ?",
      cancel: "Annuler",
      delete: "Supprimer",
      save: "Enregistrer",
    },
    budgets: {
      over: "Dépassement de",
      remaining: "restants",
      category: "Catégorie",
      cap: "Plafond",
      period: "Période",
      periodMonthly: "Mensuel",
      periodWeekly: "Hebdomadaire",
      editLimit: "Modifier le plafond",
      adjustSpent: "Ajuster les dépenses",
      adjustAuto: "Dépenses calculées automatiquement",
      addSpent: "+ Ajouter",
      removeSpent: "− Retirer",
      adjustNote: "Note (optionnel)",
      adjustApply: "Appliquer",
      manualAdjust: "Ajustement manuel",
      deleteBudget: "Supprimer le budget",
      deleteConfirm: 'Supprimer le budget "{name}" ?',
      deleteHint: "Les transactions existantes ne seront pas supprimées.",
      noAccountWarn: "Sélectionnez un compte source",
    },
    debts: {
      typeDebt: "Dette",
      typeLoan: "Prêt",
      total: "Montant total",
      remaining: "Restant dû",
      dueDate: "Échéance",
      label: "Libellé",
      sourceAccount: "Compte concerné",
      createTransaction: "Créer la transaction initiale",
      addRepayment: "+ Enregistrer un remboursement",
      repaymentTitle: "Remboursement",
      repaymentAmount: "Montant remboursé",
      repaymentDate: "Date",
      settled: "✓ Soldé",
      settledBanner: "Dette soldée !",
      showSettled: "Voir les dettes soldées",
      hideSettled: "Masquer les dettes soldées",
      amountExceedsRemaining: "Le montant dépasse le restant dû",
    },
    subscriptions: {
      name: "Nom",
      amount: "Montant",
      freq: "Fréquence",
      freqMonthly: "Mensuel",
      freqYearly: "Annuel",
      freqWeekly: "Hebdomadaire",
      nextBilling: "Prochain prélèvement",
      category: "Catégorie",
      sourceAccount: "Compte prélevé",
      paused: "En pause",
      resume: "Réactiver",
      pause: "Mettre en pause",
      cancelTransaction: "Annuler la transaction uniquement",
      disableSubscription: "Désactiver l'abonnement",
      cancelTitle: "Annuler ce prélèvement ?",
      autoDebit: "Prélèvement automatique",
      autoBadge: "Auto",
      undoTitle: "Annuler ce prélèvement automatique ?",
      undoBody: "Le montant sera recrédité sur le compte.",
      undoOnly: "Annuler uniquement",
      undoAndPause: "Annuler et désactiver",
      cancel: "Fermer",
    },
    notifications: {
      title: "Notifications",
      empty: "Aucune notification",
      markAllRead: "Tout marquer comme lu",
      lowBalanceTitle: "Solde faible",
      lowBalanceBody: "Le compte {account} est passé à {balance} € après le prélèvement {name}.",
      reminderTodayTitle: "Prélèvement aujourd'hui",
      reminderTodayBody: "{name} · {amount} € prélevé aujourd'hui.",
      reminderSoonTitle: "Prélèvement à venir",
      reminderSoonBody: "{name} · {amount} € le {date}.",
    },
    stub: {
      soon: "Bientôt disponible",
      soonDesc: "Cette section est en cours de construction.",
    },
    stocks: {
      title: "Bourse & Épargne",
      portfolio: "Mon Portefeuille",
      goals: "Objectifs d'Épargne",
      portfolioValue: "Valeur du Portefeuille",
      latentGain: "Plus-value latente",
      lastUpdated: "Mis à jour à",
      refresh: "Actualiser",
      realtime: "Cours en temps réel",
      emptyPortfolio: "Aucun actif suivi",
      emptyGoals: "Aucun objectif défini",
      addAsset: "Nouvel actif",
      addGoal: "Nouvel objectif",
      purchasePrice: "Prix d'achat",
      currentPrice: "Prix actuel",
      quantity: "Quantité",
      ticker: "Symbole / Ticker",
      assetName: "Nom de l'actif",
      assetType: "Type",
      typeStock: "Action",
      typeETF: "ETF",
      typeCrypto: "Crypto",
      typeOther: "Autre",
      totalInvested: "Total investi",
      dateAdded: "Ajouté le",
      goalReached: "✓ Objectif atteint !",
      goalRemaining: "restants",
      goalDue: "Échéance",
      addFunds: "+ Ajouter des fonds",
      goalName: "Nom de l'objectif",
      targetAmount: "Montant cible",
      currentAmount: "Montant actuel",
      goalIcon: "Icône",
      goalDate: "Échéance (optionnelle)",
      deleteAssetConfirm: "Supprimer cet actif ?",
      deleteGoalConfirm: "Supprimer cet objectif ?",
      searching: "Recherche…",
      search: "Rechercher une action, ETF, crypto…",
      noResults: "Aucun résultat",
      addToPortfolio: "+ Ajouter au portefeuille",
      alreadyInPortfolio: "✓ Dans le portefeuille",
      myPosition: "Ma Position",
      openPrice: "Ouverture",
      closePrice: "Clôture",
      highPrice: "Haut",
      lowPrice: "Bas",
      volume: "Volume",
      yearChange: "Var 1 an",
      todayChange: "aujourd'hui",
      chartUnavailable: "Données indisponibles pour ce symbole",
      refreshCooldown: "Disponible dans",
      periods: { "1J": "1J", "1S": "1S", "1M": "1M", "3M": "3M", "1A": "1A", Max: "Max" },
    },
    paywall: {
      title: "Fonctionnalité Premium",
      subtitle: "Passez à un plan supérieur pour accéder à cette fonctionnalité",
      monthly: "/ mois",
      yearly: "/ an",
      upgrade: "Passer à {plan}",
      later: "Plus tard",
      free: "Gratuit",
      pro: "Pro",
      max: "Max",
    },
    admin: {
      title: "Administration",
      badge: "ADMIN",
      users: "Utilisateurs",
      promoCodes: "Codes Promo",
      referrals: "Parrainage",
      totalUsers: "Utilisateurs",
      changePlan: "Changer de plan",
      planDuration: "Durée (jours)",
      permanent: "Permanent",
      apply: "Appliquer",
      createCode: "Créer le code",
      generateRandom: "Générer aléatoirement",
      maxUses: "Utilisations max",
      expiry: "Date d'expiration",
      deactivate: "Désactiver",
      copy: "Copier",
      copied: "Copié !",
      codeActive: "ACTIF",
      codeInactive: "INACTIF",
      uses: "Utilisations",
      search: "Rechercher un utilisateur…",
      noUsers: "Aucun utilisateur",
      noCodes: "Aucun code promo",
      noReferrals: "Aucun parrainage",
      registered: "Inscrit le",
      referredCount: "Filleuls",
      customCode: "Code personnalisé",
      totalReferrals: "Parrainages",
      rewardsGranted: "Récompenses",
      topReferrer: "Top parrain",
      referrer: "Parrain",
      referred: "Filleul",
      rewardYes: "Oui",
      rewardNo: "Non",
    },
    settings: {
      title: "Paramètres",
      profile: "Profil",
      plan: "Mon Plan",
      referral: "Parrainez un ami",
      referralTitle: "Parrainez un ami, gagnez 1 mois Pro",
      referralLink: "Votre lien unique",
      referralActive: "Filleuls actifs",
      referralRewards: "Récompenses gagnées",
      referralMonths: "mois",
      share: "Partager",
      promoCode: "Code Promo",
      promoPlaceholder: "Entrez votre code",
      promoApply: "Appliquer",
      promoSuccess: "Code appliqué — plan mis à jour !",
      promoError: "Code invalide ou déjà utilisé",
      language: "Langue",
      logout: "Se déconnecter",
      managePlan: "Gérer l'abonnement",
      planExpires: "Expire le",
      planPermanent: "Sans expiration",
      dangerZone: "Zone de danger",
      deleteAccount: "Supprimer mon compte",
      deleteConfirmTitle: "Supprimer définitivement votre compte ?",
      deleteConfirmBody: "Toutes vos données seront supprimées dans 30 jours. Vous perdrez accès immédiatement.",
      deleteConfirmStep2: 'Tapez "SUPPRIMER" pour confirmer',
      deleteConfirmWord: "SUPPRIMER",
      deleteFinal: "Supprimer définitivement",
      deleteCancel: "Annuler",
      deleteContinue: "Continuer →",
      deleteSuccess: "Votre compte sera supprimé dans 30 jours.",
      exportData: "Exporter mes données",
    },
    export: {
      title: "Exporter mes données",
      periodThisMonth: "Ce mois",
      period3M: "3 mois",
      period1Y: "1 an",
      periodAll: "Tout",
      csvTitle: "CSV",
      csvDesc: "Idéal pour Excel ou votre comptable",
      xlsxTitle: "XLSX",
      xlsxDesc: "4 onglets : Transactions, Comptes, Actifs, Budgets",
      pdfTitle: "PDF",
      pdfDesc: "Rapport formaté avec logo Wealthia",
      jsonTitle: "JSON",
      jsonDesc: "Toutes vos données — portabilité RGPD",
      download: "Télécharger",
      generating: "Génération…",
      success: "Fichier téléchargé !",
      demoBlocked: "Export indisponible en mode démo",
      sheetTransactions: "Transactions",
      sheetAccounts: "Comptes",
      sheetAssets: "Actifs",
      sheetBudgets: "Budgets",
      free: "GRATUIT",
      pro: "PRO",
      max: "MAX",
      period: "Période",
      formats: "Formats",
    },
    legal: {
      footer: "© 2026 Wealthia",
      mentions: "Mentions légales",
      cgu: "CGU",
      privacy: "Confidentialité",
      cgv: "CGV",
      lastUpdated: "Dernière mise à jour : 22 juin 2026",
      back: "Retour",
      cookieTitle: "Wealthia utilise des cookies analytiques",
      cookieBody: "pour améliorer l'expérience. Vos données financières ne sont jamais partagées.",
      cookieAccept: "Accepter",
      cookieRefuse: "Refuser",
      cookieLearnMore: "En savoir plus",
      loginConsent: "En vous connectant, vous acceptez nos",
      loginConsentAnd: "et notre",
    },
    advisor: {
      title: "Conseiller IA",
      disclaimer: "Les analyses de Wealthia AI sont fournies à titre informatif uniquement et ne constituent pas des conseils en investissement réglementés. Consultez un professionnel agréé pour toute décision financière importante.",
      newConversation: "Nouvelle conversation",
      placeholder: "Posez une question financière…",
      send: "Envoyer",
      thinking: "Analyse en cours…",
      suggestion1: "Analyse ma santé financière",
      suggestion2: "Comment réduire mes dépenses ?",
      suggestion3: "Suis-je en bonne voie pour mes objectifs ?",
      suggestion4: "Projette mon patrimoine sur 5 ans",
      greeting: "Bonjour ! Je suis votre conseiller financier personnel. Comment puis-je vous aider ?",
      lockedTitle: "Fonctionnalité Pro",
      lockedHint: "Passez à Pro pour accéder au conseiller IA personnalisé.",
      errorRetry: "Une erreur est survenue. Réessayez.",
    },
    reports: {

      title: "Rapports & Analyses",
      periodThisMonth: "Ce mois",
      periodLastMonth: "Mois dernier",
      period3M: "3 mois",
      period6M: "6 mois",
      period1Y: "1 an",
      savingsRate: "Taux d'épargne",
      savingsRateThisMonth: "Taux d'épargne ce mois",
      savingsPositive: "Vous épargnez {rate}% de vos revenus",
      savingsNegative: "Vous dépensez plus que vos revenus",
      noIncome: "Aucun revenu sur la période",
      revenues: "Revenus",
      expenses: "Dépenses",
      net: "Net",
      avgPerDay: "Moy. / Jour",
      vsLastPeriod: "vs mois-1",
      projection: "Projection fin de mois",
      projectionHint: "À ce rythme ({avg} €/jour × {days} jours)",
      repartitionRevExp: "Répartition Revenus / Dépenses",
      spent: "Dépensé",
      saved: "Épargné",
      patrimoine: "Répartition du Patrimoine",
      patrimoineTotal: "Total",
      expensesByCategory: "Dépenses par Catégorie",
      totalSpent: "Total dépensé",
      top5: "Top 5 Dépenses du Mois",
      evolution: "Évolution des derniers mois",
      netWorthEvolution: "Évolution du Patrimoine Net",
      limitedData: "Données limitées en mode démo",
      back: "Retour",
    },
  },
  en: {
    app: { name: "Wealthia", tagline: "Wealth Management" },
    demo: {
      banner: "Demo Mode — your data is not saved",
      cta: "Sign up for free →",
      button: "✦ Try the demo",
      writeBlocked: "Action disabled in demo mode",
    },
    nav: {
      home: "Home",
      transactions: "Transactions",
      accounts: "Accounts",
      stocks: "Stocks",
      advisor: "Advisor",
    },
    home: {
      hello: "Your wealth at a glance",
      overview: "Track accounts, budgets and investments in one place",
      totalBalance: "Total Balance",
      income: "Income",
      expenses: "Expenses",
      myAccounts: "My Accounts",
      monthExpenses: "Monthly Expenses",
      seeAll: "See all",
      percentOfTotal: "{p}% of total",
      quickAdd: "Add",
      quickReports: "Reports",
      quickAI: "AI",
      quickStocks: "Stocks",
    },
    auth: {
      google: "Continue with Google",
      or: "or",
      email: "Email address",
      password: "Password",
      name: "Name",
      login: "Sign in",
      signup: "Sign up",
      magicLink: "Sign in with magic link",
      magicSent: "Magic link sent! Check your inbox.",
      noAccount: "No account yet?",
      haveAccount: "Already have an account?",
    },
    transactions: {
      title: "Transactions",
      empty: "No transactions",
      emptyHint: "Add your first expense with the + button",
      loadMore: "Load more",
      aiBadge: "AI",
      filter: {
        all: "All",
        income: "Income",
        expense: "Expenses",
      },
      add: {
        titleExpense: "New expense",
        titleIncome: "New income",
        amount: "Amount",
        label: "Label",
        labelPlaceholder: "E.g. Carrefour groceries",
        category: "Category",
        account: "Account",
        noAccount: "No account",
        date: "Date",
        notes: "Notes",
        addNote: "Add a note",
        submit: "Save",
        type: {
          expense: "Expense",
          income: "Income",
        },
      },
      delete: {
        confirm: "Delete this transaction?",
        confirmCta: "Delete",
        cancel: "Cancel",
      },
    },
    accounts: {
      title: "Accounts",
      add: "Add",
      sectionAccounts: "Bank accounts",
      sectionBudgets: "Monthly Budgets",
      sectionDebts: "Debts & Loans",
      sectionSubscriptions: "Subscriptions",
      emptyAccounts: "No accounts added",
      emptyBudgets: "No budgets set",
      emptyDebts: "No debts recorded",
      emptySubscriptions: "No subscriptions tracked",
      name: "Name",
      initialBalance: "Initial balance",
      currency: "Currency",
      typeChecking: "Checking",
      typeSavings: "Savings",
      typeBooklet: "Booklet",
      typeCash: "Cash",
      typeOther: "Other",
      addAccountTitle: "New account",
      addBudgetTitle: "New budget",
      addDebtTitle: "New debt",
      addSubTitle: "New subscription",
      deleteConfirm: "Delete this item?",
      cancel: "Cancel",
      delete: "Delete",
      save: "Save",
    },
    budgets: {
      over: "Over by",
      remaining: "left",
      category: "Category",
      cap: "Cap",
      period: "Period",
      periodMonthly: "Monthly",
      periodWeekly: "Weekly",
      editLimit: "Edit limit",
      adjustSpent: "Adjust spending",
      adjustAuto: "Spending calculated automatically",
      addSpent: "+ Add",
      removeSpent: "− Remove",
      adjustNote: "Note (optional)",
      adjustApply: "Apply",
      manualAdjust: "Manual adjustment",
      deleteBudget: "Delete budget",
      deleteConfirm: 'Delete budget "{name}"?',
      deleteHint: "Existing transactions will not be deleted.",
      noAccountWarn: "Select a source account",
    },
    debts: {
      typeDebt: "Debt",
      typeLoan: "Loan",
      total: "Total amount",
      remaining: "Remaining",
      dueDate: "Due date",
      label: "Label",
      sourceAccount: "Related account",
      createTransaction: "Create initial transaction",
      addRepayment: "+ Record repayment",
      repaymentTitle: "Repayment",
      repaymentAmount: "Amount repaid",
      repaymentDate: "Date",
      settled: "✓ Settled",
      settledBanner: "Debt settled!",
      showSettled: "Show settled debts",
      hideSettled: "Hide settled debts",
      amountExceedsRemaining: "Amount exceeds remaining balance",
    },
    subscriptions: {
      name: "Name",
      amount: "Amount",
      freq: "Frequency",
      freqMonthly: "Monthly",
      freqYearly: "Yearly",
      freqWeekly: "Weekly",
      nextBilling: "Next billing",
      category: "Category",
      sourceAccount: "Payment account",
      paused: "Paused",
      resume: "Resume",
      pause: "Pause",
      cancelTransaction: "Cancel transaction only",
      disableSubscription: "Disable subscription",
      cancelTitle: "Cancel this payment?",
      autoDebit: "Automatic payment",
      autoBadge: "Auto",
      undoTitle: "Cancel this automatic payment?",
      undoBody: "The amount will be credited back to the account.",
      undoOnly: "Cancel only",
      undoAndPause: "Cancel and disable",
      cancel: "Close",
    },
    notifications: {
      title: "Notifications",
      empty: "No notifications",
      markAllRead: "Mark all as read",
      lowBalanceTitle: "Low balance",
      lowBalanceBody: "Account {account} dropped to {balance} € after {name} payment.",
      reminderTodayTitle: "Payment today",
      reminderTodayBody: "{name} · {amount} € charged today.",
      reminderSoonTitle: "Upcoming payment",
      reminderSoonBody: "{name} · {amount} € on {date}.",
    },
    stub: {
      soon: "Coming soon",
      soonDesc: "This section is under construction.",
    },
    stocks: {
      title: "Stocks & Savings",
      portfolio: "My Portfolio",
      goals: "Savings Goals",
      portfolioValue: "Portfolio Value",
      latentGain: "Unrealized Gain",
      lastUpdated: "Updated at",
      refresh: "Refresh",
      realtime: "Live prices",
      emptyPortfolio: "No assets tracked",
      emptyGoals: "No savings goals",
      addAsset: "New asset",
      addGoal: "New goal",
      purchasePrice: "Purchase price",
      currentPrice: "Current price",
      quantity: "Quantity",
      ticker: "Symbol / Ticker",
      assetName: "Asset name",
      assetType: "Type",
      typeStock: "Stock",
      typeETF: "ETF",
      typeCrypto: "Crypto",
      typeOther: "Other",
      totalInvested: "Total invested",
      dateAdded: "Added on",
      goalReached: "✓ Goal reached!",
      goalRemaining: "left",
      goalDue: "Due",
      addFunds: "+ Add funds",
      goalName: "Goal name",
      targetAmount: "Target amount",
      currentAmount: "Current amount",
      goalIcon: "Icon",
      goalDate: "Due date (optional)",
      deleteAssetConfirm: "Delete this asset?",
      deleteGoalConfirm: "Delete this goal?",
      searching: "Searching…",
      search: "Search stocks, ETFs, crypto…",
      noResults: "No results",
      addToPortfolio: "+ Add to portfolio",
      alreadyInPortfolio: "✓ In portfolio",
      myPosition: "My Position",
      openPrice: "Open",
      closePrice: "Close",
      highPrice: "High",
      lowPrice: "Low",
      volume: "Volume",
      yearChange: "1Y change",
      todayChange: "today",
      chartUnavailable: "Data unavailable for this symbol",
      refreshCooldown: "Available in",
      periods: { "1J": "1D", "1S": "1W", "1M": "1M", "3M": "3M", "1A": "1Y", Max: "Max" },
    },
    paywall: {
      title: "Premium Feature",
      subtitle: "Upgrade your plan to access this feature",
      monthly: "/ month",
      yearly: "/ year",
      upgrade: "Upgrade to {plan}",
      later: "Later",
      free: "Free",
      pro: "Pro",
      max: "Max",
    },
    admin: {
      title: "Administration",
      badge: "ADMIN",
      users: "Users",
      promoCodes: "Promo Codes",
      referrals: "Referrals",
      totalUsers: "Users",
      changePlan: "Change plan",
      planDuration: "Duration (days)",
      permanent: "Permanent",
      apply: "Apply",
      createCode: "Create code",
      generateRandom: "Generate random",
      maxUses: "Max uses",
      expiry: "Expiry date",
      deactivate: "Deactivate",
      copy: "Copy",
      copied: "Copied!",
      codeActive: "ACTIVE",
      codeInactive: "INACTIVE",
      uses: "Uses",
      search: "Search a user…",
      noUsers: "No users",
      noCodes: "No promo codes",
      noReferrals: "No referrals",
      registered: "Registered",
      referredCount: "Referrals",
      customCode: "Custom code",
      totalReferrals: "Referrals",
      rewardsGranted: "Rewards",
      topReferrer: "Top referrer",
      referrer: "Referrer",
      referred: "Referred",
      rewardYes: "Yes",
      rewardNo: "No",
    },
    settings: {
      title: "Settings",
      profile: "Profile",
      plan: "My Plan",
      referral: "Refer a friend",
      referralTitle: "Refer a friend, earn 1 month Pro",
      referralLink: "Your unique link",
      referralActive: "Active referrals",
      referralRewards: "Rewards earned",
      referralMonths: "months",
      share: "Share",
      promoCode: "Promo Code",
      promoPlaceholder: "Enter your code",
      promoApply: "Apply",
      promoSuccess: "Code applied — plan updated!",
      promoError: "Invalid or already used code",
      language: "Language",
      logout: "Sign out",
      managePlan: "Manage subscription",
      planExpires: "Expires on",
      planPermanent: "No expiry",
      dangerZone: "Danger zone",
      deleteAccount: "Delete my account",
      deleteConfirmTitle: "Permanently delete your account?",
      deleteConfirmBody: "All your data will be deleted within 30 days. You will lose access immediately.",
      deleteConfirmStep2: 'Type "DELETE" to confirm',
      deleteConfirmWord: "DELETE",
      deleteFinal: "Permanently delete",
      deleteCancel: "Cancel",
      deleteContinue: "Continue →",
      deleteSuccess: "Your account will be deleted within 30 days.",
      exportData: "Export my data",
    },
    export: {
      title: "Export my data",
      periodThisMonth: "This month",
      period3M: "3 months",
      period1Y: "1 year",
      periodAll: "All",
      csvTitle: "CSV",
      csvDesc: "Perfect for Excel or your accountant",
      xlsxTitle: "XLSX",
      xlsxDesc: "4 tabs: Transactions, Accounts, Assets, Budgets",
      pdfTitle: "PDF",
      pdfDesc: "Formatted report with Wealthia logo",
      jsonTitle: "JSON",
      jsonDesc: "All your data — GDPR portability",
      download: "Download",
      generating: "Generating…",
      success: "File downloaded!",
      demoBlocked: "Export unavailable in demo mode",
      sheetTransactions: "Transactions",
      sheetAccounts: "Accounts",
      sheetAssets: "Assets",
      sheetBudgets: "Budgets",
      free: "FREE",
      pro: "PRO",
      max: "MAX",
      period: "Period",
      formats: "Formats",
    },
    legal: {
      footer: "© 2026 Wealthia",
      mentions: "Legal notice",
      cgu: "Terms of use",
      privacy: "Privacy policy",
      cgv: "Terms of sale",
      lastUpdated: "Last updated: June 22, 2026",
      back: "Back",
      cookieTitle: "Wealthia uses analytics cookies",
      cookieBody: "to improve your experience. Your financial data is never shared.",
      cookieAccept: "Accept",
      cookieRefuse: "Decline",
      cookieLearnMore: "Learn more",
      loginConsent: "By signing in, you agree to our",
      loginConsentAnd: "and our",
    },
    advisor: {
      title: "AI Advisor",
      disclaimer: "Wealthia AI analyses are for informational purposes only and do not constitute regulated investment advice. Consult a licensed professional for any major financial decision.",
      newConversation: "New conversation",
      placeholder: "Ask a financial question…",
      send: "Send",
      thinking: "Analyzing…",
      suggestion1: "Analyze my financial health",
      suggestion2: "How can I reduce my expenses?",
      suggestion3: "Am I on track for my goals?",
      suggestion4: "Project my wealth over 5 years",
      greeting: "Hello! I'm your personal financial advisor. How can I help you?",
      lockedTitle: "Pro Feature",
      lockedHint: "Upgrade to Pro to access the personalized AI advisor.",
      errorRetry: "An error occurred. Please try again.",
    },
    reports: {

      title: "Reports & Analysis",
      periodThisMonth: "This month",
      periodLastMonth: "Last month",
      period3M: "3 months",
      period6M: "6 months",
      period1Y: "1 year",
      savingsRate: "Savings rate",
      savingsRateThisMonth: "Savings rate this month",
      savingsPositive: "You're saving {rate}% of your income",
      savingsNegative: "You're spending more than you earn",
      noIncome: "No income in this period",
      revenues: "Income",
      expenses: "Expenses",
      net: "Net",
      avgPerDay: "Avg. / Day",
      vsLastPeriod: "vs last period",
      projection: "End of month projection",
      projectionHint: "At this rate ({avg} €/day × {days} days)",
      repartitionRevExp: "Income / Expense breakdown",
      spent: "Spent",
      saved: "Saved",
      patrimoine: "Wealth Breakdown",
      patrimoineTotal: "Total",
      expensesByCategory: "Expenses by Category",
      totalSpent: "Total spent",
      top5: "Top 5 Expenses This Month",
      evolution: "Monthly evolution",
      netWorthEvolution: "Net Worth Evolution",
      limitedData: "Limited data in demo mode",
      back: "Back",
    },
  },
} as const;

export type Strings = typeof translations.fr;

function getNestedValue(obj: Record<string, unknown>, path: string): string {
  const keys = path.split(".");
  let current: unknown = obj;
  for (const key of keys) {
    if (current && typeof current === "object" && key in (current as Record<string, unknown>)) {
      current = (current as Record<string, unknown>)[key];
    } else {
      return path;
    }
  }
  return typeof current === "string" ? current : path;
}

function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) =>
    k in vars ? String(vars[k]) : `{${k}}`,
  );
}

function readLang(): Language {
  if (typeof window === "undefined") return "fr";
  const stored = window.localStorage.getItem("wealthia_lang");
  return stored === "en" ? "en" : "fr";
}

export function useTranslation() {
  const lang: Language = readLang();
  const strings = translations[lang];

  const t = (key: string, vars?: Record<string, string | number>): string => {
    const raw = getNestedValue(strings as unknown as Record<string, unknown>, key);
    return interpolate(raw, vars);
  };

  const setLanguage = (l: Language) => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem("wealthia_lang", l);
    window.location.reload();
  };

  return { t, strings, lang, setLanguage };
}
