/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal.mentions-legales'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCgvRouteImport } from './routes/legal.cgv'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedConseillerRouteImport } from './routes/_authenticated/conseiller'
import { Route as AuthenticatedComptesRouteImport } from './routes/_authenticated/comptes'
import { Route as AuthenticatedBourseRouteImport } from './routes/_authenticated/bourse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiStripeCreateCheckoutSessionRouteImport } from './routes/api/stripe/create-checkout-session'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConseillerRoute = AuthenticatedConseillerRouteImport.update({
  id: '/conseiller',
  path: '/conseiller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComptesRoute = AuthenticatedComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBourseRoute = AuthenticatedBourseRouteImport.update({
  id: '/bourse',
  path: '/bourse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiStripeCreateCheckoutSessionRoute =
  ApiStripeCreateCheckoutSessionRouteImport.update({
    id: '/api/stripe/create-checkout-session',
    path: '/api/stripe/create-checkout-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bourse': typeof AuthenticatedBourseRoute
  '/comptes': typeof AuthenticatedComptesRoute
  '/conseiller': typeof AuthenticatedConseillerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/api/stripe/create-checkout-session': typeof ApiStripeCreateCheckoutSessionRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bourse': typeof AuthenticatedBourseRoute
  '/comptes': typeof AuthenticatedComptesRoute
  '/conseiller': typeof AuthenticatedConseillerRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/stripe/create-checkout-session': typeof ApiStripeCreateCheckoutSessionRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bourse': typeof AuthenticatedBourseRoute
  '/_authenticated/comptes': typeof AuthenticatedComptesRoute
  '/_authenticated/conseiller': typeof AuthenticatedConseillerRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/stripe/create-checkout-session': typeof ApiStripeCreateCheckoutSessionRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/bourse'
    | '/comptes'
    | '/conseiller'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/mentions-legales'
    | '/api/stripe/create-checkout-session'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/bourse'
    | '/comptes'
    | '/conseiller'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/mentions-legales'
    | '/'
    | '/api/stripe/create-checkout-session'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/bourse'
    | '/_authenticated/comptes'
    | '/_authenticated/conseiller'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/mentions-legales'
    | '/_authenticated/'
    | '/api/stripe/create-checkout-session'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  ApiStripeCreateCheckoutSessionRoute: typeof ApiStripeCreateCheckoutSessionRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conseiller': {
      id: '/_authenticated/conseiller'
      path: '/conseiller'
      fullPath: '/conseiller'
      preLoaderRoute: typeof AuthenticatedConseillerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comptes': {
      id: '/_authenticated/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof AuthenticatedComptesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bourse': {
      id: '/_authenticated/bourse'
      path: '/bourse'
      fullPath: '/bourse'
      preLoaderRoute: typeof AuthenticatedBourseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/stripe/create-checkout-session': {
      id: '/api/stripe/create-checkout-session'
      path: '/api/stripe/create-checkout-session'
      fullPath: '/api/stripe/create-checkout-session'
      preLoaderRoute: typeof ApiStripeCreateCheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBourseRoute: typeof AuthenticatedBourseRoute
  AuthenticatedComptesRoute: typeof AuthenticatedComptesRoute
  AuthenticatedConseillerRoute: typeof AuthenticatedConseillerRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBourseRoute: AuthenticatedBourseRoute,
  AuthenticatedComptesRoute: AuthenticatedComptesRoute,
  AuthenticatedConseillerRoute: AuthenticatedConseillerRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LegalCguRoute: LegalCguRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  ApiStripeCreateCheckoutSessionRoute: ApiStripeCreateCheckoutSessionRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
